import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Settings",
  description: "Generated by create next app",
};

export default function () {
  return <div></div>;
}
